---
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: kind-ha
networking:
  podSubnet: "10.209.0.0/16"
  serviceSubnet: "10.208.0.0/16"
nodes:
  - role: control-plane
  - role: control-plane
  - role: control-plane
  - role: worker
  - role: worker
  - role: worker
